import type { ChallengeDef } from "./arena/types";
import type { ArenaEvent, Chat, CustomSkill, Project, Schedule } from "./types";

export type GuideTarget = "composer" | "attachments" | "customize" | "projects" | "new-project" | "mode" | "schedule" | "scheduled" | "save-skill";
export interface PracticeExercise extends ChallengeDef {
  category: "prompting" | "features";
  guide: { target: GuideTarget; text: string; after?: string }[];
}
const transcript = { kind: "file" as const, id: "meeting", filename: "meeting-notes.txt", title: "Meeting notes", mediaType: "text/plain", body: "We agreed to publish the guide on Friday. The draft needs a shorter introduction. I will revise the introduction tomorrow. We still need to decide whether to include a video. The next review is Thursday." };
const exercise = (p: Omit<PracticeExercise, "points" | "minutes" | "checks" | "hints" | "order" | "teaches">, order: number): PracticeExercise => ({ ...p, order, points: 0, minutes: 0, checks: [], hints: [], teaches: p.hook });

export const PRACTICE_EXERCISES: PracticeExercise[] = [
  exercise({ slug: "practice-prompting", title: "Shape an answer", category: "prompting", hook: "See how your instructions change an AI response.", badges: ["constraints", "audience"], brief: "Build a request with the prompt chips, then send it. Change the format or audience and try again. You can edit the request in your own words, too.", deliverable: "Try two different requests and compare the responses.", behaviors: [{ id: "requests", label: "Try two requests", event: "message_sent", minCount: 2 }], guide: [{ target: "composer", text: "The chips fill the message box. Edit the request or send it as it is." }] }, 1),
  exercise({ slug: "practice-create-skill", title: "Create a skill", category: "features", hook: "Save an instruction so you can use it again.", badges: ["skills"], brief: "Create a skill that turns meeting notes into **Decisions**, **Next steps**, and **Open questions**. Choose any name and save it.\n\nAdd the supplied notes to a message and use your new skill with **/name**.", deliverable: "Save a skill, then use it on the supplied notes.", materials: [transcript], behaviors: [{ id: "created", label: "Save a new skill", event: "skill_created" }, { id: "used", label: "Use that skill in a message", event: "skill_invoked" }], guide: [{ target: "customize", text: "Open Customize, then Skills → Add. Save the instructions for your skill." }, { target: "composer", text: "Type / to choose your saved skill, and add the meeting notes.", after: "created" }] }, 2),
  exercise({ slug: "practice-use-skill", title: "Use a ready-made skill", category: "features", hook: "Use saved instructions without writing them again.", badges: ["skills"], brief: "Add the meeting notes to your message. Type **/** and choose **meeting-notes**, then send it. Notice how the skill supplies the format.", deliverable: "Use the meeting-notes skill with the supplied file.", materials: [transcript], behaviors: [{ id: "file", label: "Add the meeting notes", event: "file_attached", detail: "meeting-notes.txt" }, { id: "used", label: "Use /meeting-notes", event: "skill_invoked", detail: "meeting-notes" }], guide: [{ target: "composer", text: "Tap the supplied file to attach it, then type / to choose meeting-notes." }] }, 3),
  exercise({ slug: "practice-files", title: "Give AI a file", category: "features", hook: "Bring your own material into a conversation.", badges: ["file-upload"], brief: "Add the supplied notes to the message box, then ask a question about them. You can tap the file or drag it in.", deliverable: "Send the supplied file with a question.", materials: [transcript], behaviors: [{ id: "file", label: "Send the meeting-notes file", event: "file_attached", detail: "meeting-notes.txt" }], guide: [{ target: "attachments", text: "The + menu adds files from your device. For this exercise, tap the supplied meeting notes." }] }, 4),
  exercise({ slug: "practice-project", title: "Set up a project", category: "features", hook: "Keep related chats, files, and instructions together.", badges: ["projects", "custom-instructions"], brief: "Create a project with any name. Give it an instruction you want it to follow, such as keeping explanations brief.\n\nStart a chat inside the project and ask a question without repeating that instruction.", deliverable: "Create a project with instructions and send a message inside it.", behaviors: [{ id: "project", label: "Create a project with instructions", event: "project_created" }, { id: "inside", label: "Send a message inside the project", event: "chat_in_project" }], guide: [{ target: "new-project", text: "Create a project here. Add its name and instructions, then start a chat inside it." }, { target: "composer", text: "Ask a question. The project supplies its saved instructions.", after: "project" }] }, 5),
  exercise({ slug: "practice-connect", title: "Connect Gmail", category: "features", hook: "Give AI access to information in a connected tool.", badges: ["connectors"], brief: "Open **Customize → Connectors** and connect **Gmail**. Ask the assistant to read an unread email. This is a sample inbox for practice.", deliverable: "Read an email through the Gmail connector.", behaviors: [{ id: "read", label: "Read from the practice inbox", event: "connector_used", detail: "gmail" }], guide: [{ target: "customize", text: "Open Customize → Connectors and connect Gmail. Then ask about an unread email." }] }, 6),
  exercise({ slug: "practice-cowork", title: "Try Cowork", category: "features", hook: "Let AI plan and carry out a task.", badges: ["cowork", "file-upload"], brief: "Switch the composer from **Chat** to **Cowork**. Give it the supplied notes and ask it to prepare a plan for the next review. Watch it work through the task.", deliverable: "Send the notes as a Cowork task.", materials: [transcript], behaviors: [{ id: "cowork", label: "Send a task in Cowork", event: "cowork_on" }, { id: "file", label: "Supply the meeting notes", event: "file_attached", detail: "meeting-notes.txt" }], guide: [{ target: "mode", text: "Switch Chat to Cowork, add the notes, and describe what you want done." }] }, 7),
  exercise({ slug: "practice-schedule", title: "Schedule a task", category: "features", hook: "Set up a task to repeat and inspect a test run.", badges: ["cowork"], brief: "Switch to **Cowork**. Open **Schedule**, describe a task, and choose **Daily**.\n\nOpen **Scheduled**, select **Run now**, and wait for the reply. This workspace simulates scheduled tasks; it does not run them in the background.", deliverable: "Save a daily schedule and complete a test run.", behaviors: [{ id: "created", label: "Save a daily schedule", event: "schedule_created" }, { id: "ran", label: "Complete its test run", event: "schedule_run" }], guide: [{ target: "mode", text: "Switch to Cowork. Schedule appears below the message box." }, { target: "scheduled", text: "Open Scheduled and choose Run now to test your task.", after: "created" }] }, 8),
  exercise({ slug: "practice-save-task", title: "Turn a task into a skill", category: "features", hook: "Reuse a task that already works.", badges: ["cowork", "skills"], brief: "Run a task in **Cowork**. When it finishes, choose **Save as skill** above the conversation.\n\nStart a **new chat** and use the saved skill with **/name**.", deliverable: "Save a Cowork task as a skill and use it in a new chat.", behaviors: [{ id: "saved", label: "Save a completed task as a skill", event: "skill_from_cowork" }, { id: "used", label: "Use the saved skill in a new chat", event: "skill_invoked" }], guide: [{ target: "mode", text: "Switch to Cowork and send a task. After it finishes, Save as skill appears above the chat." }, { target: "composer", text: "Choose New, then type / and select the skill you just saved.", after: "saved" }] }, 9),
];

export const getPractice = (slug: string) => PRACTICE_EXERCISES.find((p) => p.slug === slug) ?? null;

/** Practice records observed actions, never an AI grade or competitive points. */
export function practiceChecks(exercise: PracticeExercise, events: ArenaEvent[], workspace?: { chats: Chat[]; skills: CustomSkill[]; projects: Project[]; schedules: Schedule[] }) {
  const chats = workspace?.chats.filter((c) => events.some((e) => e.chatId === c.id)) ?? [];
  const answered = (id?: string) => chats.some((c) => c.id === id && c.messages.at(-1)?.role === "assistant");
  return exercise.behaviors.map((b) => {
    let hits = events.filter((e) => e.type === b.event && (!b.detail || e.detail === b.detail));
    if (workspace) {
      if (b.event === "skill_created") hits = hits.filter((e) => workspace.skills.some((s) => s.name === e.detail && s.prompt.trim()));
      if (b.event === "project_created") hits = hits.filter((e) => workspace.projects.some((p) => p.id === e.detail && p.instructions.trim()));
      if (b.event === "chat_in_project") hits = hits.filter((e) => answered(e.chatId) && events.some((x) => x.type === "project_created" && x.detail === e.detail));
      if (b.event === "schedule_created") hits = hits.filter((e) => workspace.schedules.some((s) => s.id === e.detail && s.cadence === "daily"));
      if (b.event === "schedule_run") hits = hits.filter((e) => answered(e.chatId) && workspace.schedules.some((s) => s.id === e.detail && s.cadence === "daily" && events.some((x) => x.type === "schedule_created" && x.detail === s.id)));
      if (["message_sent", "file_attached", "cowork_on", "skill_invoked", "connector_used"].includes(b.event)) hits = hits.filter((e) => answered(e.chatId));
      if (exercise.slug === "practice-create-skill" && b.event === "skill_invoked") hits = hits.filter((e) => events.some((x) => x.type === "skill_created" && x.detail === e.detail) && events.some((x) => x.type === "file_attached" && x.detail === "meeting-notes.txt" && x.chatId === e.chatId));
      if (exercise.slug === "practice-save-task" && b.event === "skill_invoked") hits = hits.filter((e) => events.some((x) => x.type === "skill_from_cowork" && x.detail === e.detail && x.chatId !== e.chatId));
      if (exercise.slug === "practice-prompting") {
        const prompts = new Set(chats.flatMap((c) => c.messages.filter((m) => m.role === "user").map((m) => m.parts.filter((p) => p.type === "text").map((p) => p.text).join(" ").trim())));
        if (prompts.size < 2) hits = hits.slice(0, 1);
      }
    }
    return { ...b, pass: hits.length >= (b.minCount ?? 1) };
  });
}
